name: "Hailo Whisper"
description: "Hailo Whisper model for HA addon"
version: "1.0.0"
slug: "hailo_whisper_addon"
init: false
arch:
  - aarch64
startup: services
ports:
  10300/tcp: 10300
devices: ["/dev/hailo0"]
udev: true
map:	 
  - "media:rw"	 
  - "addon_config:rw"
options:
  hw_arch: "auto"
  model_variant: "base"
  language: "auto"
  model_auto_download: true
  vdevice_group_id: "HAILO_SHARED"
  multi_process_service: false
schema:
  hw_arch: list(auto|hailo8|hailo8l|hailo10h)
  model_variant: list(base|tiny|tiny.en)
  language: list(auto|zh|en)
  model_auto_download: bool
  vdevice_group_id: str
  multi_process_service: bool
